TARGET_CATEGORIES = {
    "kuafor",
    "kuaför",
    "berber",
    "guzellik salonu",
    "güzellik salonu",
    "oto yikama",
    "oto yıkama",
    "oto servis",
    "hali yikama",
    "halı yıkama",
    "klima servisi",
    "cicekci",
    "çiçekçi",
    "pet kuaforu",
    "pet kuaförü",
    "kafe",
    "restoran",
    "spor salonu",
    "ozel kurs",
    "özel kurs",
    "temizlik firmasi",
    "temizlik firması",
}

REGULATED_KEYWORDS = {
    "avukat",
    "hukuk",
    "noter",
    "klinik",
    "hastane",
    "doktor",
    "diş",
    "dis",
    "eczane",
    "ilaç",
    "ilac",
    "finans",
    "banka",
    "kredi",
    "sigorta",
    "yatirim",
    "yatırım",
    "siyasi",
    "parti",
    "dernek",
    "vakif",
    "vakıf",
    "cami",
    "kilise",
    "alkol",
    "bar",
    "pavyon",
    "bahis",
    "kumar",
    "silah",
    "yetişkin",
    "yetiskin",
}

FORBIDDEN_CLAIMS = {
    "seo garantili",
    "google'da ilk sıra",
    "googleda ilk sıra",
    "google'da ilk siraya",
    "googleda ilk siraya",
    "ilk sıraya çıkarırız",
    "ilk siraya cikaririz",
    "kesin müşteri",
    "kesin musteri",
    "garantili satış",
    "garantili satis",
}

SOCIAL_OR_DIRECTORY_HOSTS = {
    "facebook.com",
    "instagram.com",
    "linktr.ee",
    "wa.me",
    "whatsapp.com",
    "business.site",
    "sites.google.com",
    "maps.google.com",
    "goo.gl",
}

CATEGORY_WEIGHTS = {
    "kuafor": 10,
    "kuaför": 10,
    "berber": 10,
    "guzellik salonu": 9,
    "güzellik salonu": 9,
    "oto yikama": 8,
    "oto yıkama": 8,
    "oto servis": 8,
    "hali yikama": 8,
    "halı yıkama": 8,
    "klima servisi": 8,
    "cicekci": 7,
    "çiçekçi": 7,
    "pet kuaforu": 8,
    "pet kuaförü": 8,
    "kafe": 6,
    "restoran": 6,
    "spor salonu": 7,
    "ozel kurs": 7,
    "özel kurs": 7,
    "temizlik firmasi": 8,
    "temizlik firması": 8,
}
